prometheus-node-exporter:
  resources:
    requests:
      cpu: 100m
      memory: 30Mi
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
