apiVersion: fogguru.eu/v1                                                                                
kind: MultiClusterService                                                                                
metadata:                                                                                                
  name: preferred                                                                                            
  annotations:                                                                                           
    io.cilium/global-service: "false"                                                                     
spec:                                                                                                    
  selector:                                                                                              
    app: preferred                                                                                           
    tier: backend                                                                                        
  ports:                                                                                                 
  - protocol: TCP                                                                                        
    port: 80                                                                                             
    targetPort: http
  type: NodePort