apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cloudprovisioners.fogguru.eu
spec:
  scope: Cluster
  group: fogguru.eu
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: CloudProvisioner
    plural: cloudprovisioners
    singular: cloudprovisioner
    shortNames:
      - cpro
      - cp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
