apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appreschedulers.fogguru.eu
spec:
  scope: Cluster
  group: fogguru.eu
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: AppRescheduler
    plural: appreschedulers
    singular: apprescheduler
    shortNames:
      - appresch
      - appres
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
