apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterdeployments.fogguru.eu
spec:
  scope: Namespaced
  group: fogguru.eu
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: MultiClusterDeployment
    plural: multiclusterdeployments
    singular: multiclusterdeployment
    shortNames:
      - mcd
      - mcds
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
